name: Android CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout⤵️
      uses: actions/checkout@v4.1.0
    - name: Setup Java JDK
      uses: actions/setup-java@v4.2.1
    - name: Gradle
      run: ./gradlew build
    - name: Upload Artifact
      uses: actions/upload-artifact@v4.3.3
      with:
        name: ProductSurvey.apk
        path: app/build/outputs/apk/debug/apk-debug.apk
